### ISSUE TITLE
followed instructions but getting no sound

### ISSUE THREAD

**Issue by irish-moss** [publicsamples/Oi-Grandad#1]
I followed the instructions for component and modular sample folder in the application support folder. 
I'm getting no sound or presets and was unable to point the synth in the right direction
any suggestions?

**Comment by modularsamples** [comment]
Hi there. 

You may have already tried this, but the presets are accessed by pressing the page 2 button (not very intuitive, I know). 
You could also try dragging an audio file into the waveform area, as shown in the link below:

https://raw.githubusercontent.com/publicsamples/Oi-Grandad/main/oi%20grandad/wiki-images/drag.png

If none of that works, it would be really helpful if you could give me some basic info like your DAW (including version number) and what OS you're running. So far I've tested in logic and Ableton and both seem fine..

Cheers
Rick

**Comment by irish-moss** [comment]
Hi Rick
Im on Ableton 10.1.4 and mac Catalina

Should the synth play midi when opened?
It looks quite cool.
Rob

**Comment by irish-moss** [comment]
Thanks for quick reply

**Comment by modularsamples** [comment]
It responds to midi, or you can press the drone button for continuous playback. Thing is,  in its initial state you won't here anything, you need to load in a wav first..

Any luck finding the presets? I just fired it up in Ableton 11, on Big Sur and it's working fine.. If you're still having trouble, maybe you could send me a screenshot, might help if I can see what's going  on.

**Comment by irish-moss** [comment]
Ok so its manually set up. I'll try instructions when i go back in

**Comment by modularsamples** [comment]
I'm closing this issue as the synth has had several updates since, feel free to reopen it if you're still having trouble though!
