### ISSUE TITLE
Linux build with older GLIBC

### ISSUE THREAD

**Issue by dromer** [publicsamples/Oi-Grandad#11]
It seems you've built your Linux version on quite a new system, which means it cannot run on even slightly older machines.

Please consider building on ie. Debian 11 or Ubuntu 20.04 instead.

**Comment by modularsamples** [comment]
Okay, I'll look into it for the next version.

**Comment by davidhealey** [comment]
I run my builds on Linux Mint 18, which seems sufficiently old to work for most people. If I remember correctly the only extra step I had to do was find a suitable version of gcc.

**Comment by modularsamples** [comment]
Thanks David, I'll get to this sometime in the next couple of days. 

By the way, have you come across this? Seems to be a way round these backwards compatibility issues. 

https://github.com/wheybags/glibc_version_header

**Comment by davidhealey** [comment]
@modularsamples That looks interesting, I hadn't seen it before. Thanks!

**Comment by modularsamples** [comment]
Okay, sorry this took me so long.. The latest version has been built with Ubuntu 18, tested in reaper and it seems to work.

https://github.com/publicsamples/Oi-Grandad/releases/download/0.99/oi.grandad.vst3.Linux.tar.xz

Linux audio is is bit of a mystery to me, however (don't make me JACK) so if a Linux enthusiast could give it a once over before I close the issue that would be great.

**Comment by dromer** [comment]
Thnx! loads alright in carla over here.

Only thing that doesn't work is drag-n-drop of samples (but that's an extremely non-trivial thing to solve). Loading from filebrowser works fine.
