### ISSUE TITLE
Oi Grandad on Win11 no sounds at all

### ISSUE THREAD

**Issue by bobe94** [publicsamples/Oi-Grandad#21]
I don't know why, but the plugin has no sound at all in Ableton 11, Win11.
The installation is correct. I can see a load the VST in ableton. I can enter the factory presets folder and choose one of them. But there is no output sounds. ( i checked if the samples in the folder have sounds and.. yes, if i open them i can listen to them).

Any advice?

**Comment by modularsamples** [comment]
Hi,

I just checked in Ableton and it's working fine here.. Have you tried importing your own sounds? (drag and drop, or right click on the sample box). 

The synth also needs some sort of input, so you need to press a note, or click on the drone switch (sorry if this is really obvious, but some people miss this). See the [tutorial videos](https://youtube.com/playlist?list=PL8Rp79UJ5uBC-SntUW93i3953yPq0DeSF) for more info.

Hope that helps, if not try sending a screenshot of the synth in your DAW and I'll have a look.

Cheers
Rick

**Comment by modularsamples** [comment]
Closed due to lack of response
