### ISSUE TITLE
Font Sizes

### ISSUE THREAD

**Issue by tank-trax** [publicsamples/Oi-Grandad#24]
Using HISE 3 on Debian 11

I am able to build OI Grandad. Had to change paths for IPP. However the fonts appear to be too large. Could you offer any clues how to adjust this globally?

![image](https://user-images.githubusercontent.com/41337033/218569812-e048b809-74eb-41cc-bbb1-9f2f55759998.png)

**Comment by RickTaylor79** [comment]
Try a newer version, the font issue was resolved quite awhile ago. 

Or, if you prefer this version for whatever reason you could:

1. enter "Label" into the component list search box (this will bring up 90% of the text used)
2. Select them all
3. in the property editor, change to a standard linux font (oxygen should be fine..). 

FYI, there's no need for IPP here.

**Comment by tank-trax** [comment]
Try a newer version of what? HISE or OI Grandad?

**Comment by RickTaylor79** [comment]
Ah, I think I know what's going on here.. I left an earlier version of the UI in the project and It looks like you opened this (very sloppy on my part).

From the file menu, select "Open XML", navigate to  XmlPresetBackups folder select "oi grandad.xml". This is the up-to date version that fixes the fonts (and several other things).

**Comment by tank-trax** [comment]
I tried that. It looks better, however there was an error loading script gran2, gran 3 and gran 4

**Comment by RickTaylor79** [comment]
Ive seen this before, usually after opening the project on another OS. It shouldn't be a problem. The error should go away if you save and restart. If you run into any problems though, try the archive instead ((file menu, open recent archive, oi grandad).

By the way, did the [release version](https://github.com/publicsamples/Oi-Grandad/releases/tag/1.1.3) not work for you? It was built with Ubuntu 20, so should be compatible with Debian 11 afaik.

**Comment by tank-trax** [comment]
The hosted binary works, I wanted a Standalone and VST2 :-) also because I wanted to see how it built locally

**Comment by RickTaylor79** [comment]
Gotcha. Please excuse the mess of a project. If I'd known people were likely to actually open the thing I'd have tidied up first!

**Comment by tank-trax** [comment]
after further testing the one with the skewed gui played the audio but the one that displayed well although it loaded the presets, did not load the wave files

no need to apologize, the Oi, Grandad! v1.1.3 vst3 release works, will close this ticket and continue following this project

thanks
