### ISSUE TITLE
Drone mode always active at startup with Logic Pro

### ISSUE THREAD

**Issue by PaoloQuaglino77** [publicsamples/Oi-Grandad#25]
Hi,using Logic Pro 10.7.2 and Grandad 1.1.3
Even if I save the Logic project with drone mode off, when I open it again drone mode is on
Fix: manually move the switch ON then OFF to stop the sound, or use automation

**Comment by RickTaylor79** [comment]
Thanks for the report. I'll fix this for the next release.

**Comment by RickTaylor79** [comment]
Fixed in 1.1.4
