### ISSUE TITLE
AudioResources.dat cannot be found

### ISSUE THREAD

**Issue by psycoMixer** [publicsamples/Oi-Grandad#26]
### Discussed in https://github.com/publicsamples/Oi-Grandad/discussions/13

<div type='discussions-op-text'>

<sup>Originally posted by **GuichardVictor42** November 20, 2022</sup>
Hey, I downloaded Oi! Grandad today when I saw it in a Venus Theory video, but when trying to load the plugin into Ableton Live, the interface shows up but is all blurred and I get the following error message: 

"The file C:\Users\victo\AppData\Roaming\modularsamples\oi grandad\AudioResources.dat couldn't be found."

When downloading, I just put the unzipped folder '"oi.grandad.vst3.win" that only contains the file "oi grandad.vst3" in the folder by which Ableton accesses all the VST3s on my computer (which is just C:\VST3 Installations in my case), so I don't really know where I should find this additionnal .dat file. Could you please help me with this ?

Thanks in advance and have a great day !

V. Guichard</div>

**Comment by psycoMixer** [comment]
Same problem with an M1 Mac, presets are shown but when I choose one, no audio files are loaded into the windows. I can load files manually but I don't know which audio files match the presets. The program works fine once I have loaded audio files manually, there should be a way to load the preset audio files into the proper locations, this isn't happening. If I knew where they are suppose to be, I could move the files to that location, then they should load with the preset. Does anyone know where the audio files should be located?

**Comment by RickTaylor79** [comment]
All samples and presets should be in:

/Users/_YOURUSERNAME_/Library/Application Support/modularsamples/oi grandad

If you're having trouble, try this installer package. It will do it for you :) 

https://github.com/publicsamples/Oi-Grandad/releases/download/1.1.3/Additional.Content.Mac.pkg.zip

**Comment by psycoMixer** [comment]
Beautiful, the installer package did the trick. Thanks a lot, Rick, much
appreciated. Sounds great. However, there are a lot of sound files missing.
Most of the Factory sounds are there but most of the others have only a few
files. The screen shows the file names but they aren't loaded. I did a
manual search for the files, not found in any of the packages folders.
Anyhow, I can at least use some of the presets. Are the remainder of the
sound files available for download?

**Comment by RickTaylor79** [comment]
Sorry, I'm not really following you. Which presets are you talking about? there are only 10 included with the package on github. I sell an expansion pack that has a bunch more, did you buy that?

**Comment by psycoMixer** [comment]
No, I didn't. When I click on the red presets icon, it displays a number of
categories, the presets downloaded through the link you provided are mostly
in the "Factory" category, there are very few presets in any of the other
categories. I probably won't use this product very often, I have better
purchased products such as Imaginando's FRMS which also has add on packs
available, and Steinberg's padshop2 for which I purchased the granular
guitar presets which is just awesome. All of the programs allow me to use
my own sample files if I wish. My newest purchase is a granular module for
Cherry Audio's Voltage Modular. This module allows me to use my own samples
or I can record live right into the program, very convenient. The Granular
Guitars package is my favorite, hands down! I create samples using au
plugins on Logic, then I use the multitude of effects I have to produce the
end product, seldom sounds much like the original, they only supply the
base sound.
Thanks for your assistance, much appreciated.

**Comment by RickTaylor79** [comment]
No idea. Try this.

Delete the Oi grandad folder found in /Users/YOURUSERNAME/Library/Application Support/modularsamples, then reinstall. 

Yup, those plugins by established industry giants are pretty cool.
