### ISSUE TITLE
Feature Request

### ISSUE THREAD

**Issue by BubsonGH** [publicsamples/Oi-Grandad#27]
Id like to request Oi Grandad support embedding/saving the imported samples within DAW based presets.

These days many people like myself save all plugin presets/ chains at the DAW level. This saves a lot of headaches having to backup presets from the sometimes endless amount of plugins you can build up.

When it comes to plugins that support the importation of samples, having the option to have them save within DAW based presets are a very nice feature to keep everything you create in one preset reliant upon the one preset file itself.

Couple other plugins that have done this is phase plant and the mangle.

Thanks
Dan

**Comment by RickTaylor79** [comment]
Hi Dan,

Thanks for the suggestion, it's a good idea. Raises a lot of questions though as I've no idea how to implement it. It's not clear if I could do this with native presets, let alone DAW specific ones. 

Oi, Grandad!'s file and preset handling really could use an overhaul anyway, so I'll look into then.

Cheers
Rick

**Comment by BubsonGH** [comment]
Thanks Rick,

I wish I could help you but the world of coding is a mystery to me.

I can't say I have ever seen another vst have its native presets implemented as standard to be a DAW presets, actually.. tell a lie, I believe I have seen plugin alliance do this.. 

But most vsts such as phase plant and the mangle both have their own file structure for native presets and samples, but they also support the action of saving the sample within the DAW based preset itself.. searching file systems for said sample becomes no longer needed.

I have been speaking about this to other companies and actually just sent a video to uvi to explain it better.. here is the link if it happens to help you. https://www.youtube.com/watch?v=cnMmd4RPcIc

Cheers
Dan
