### ISSUE TITLE
Modulator control title is 'mutl'

### ISSUE THREAD

**Issue by ajmoorhouse** [publicsamples/Oi-Grandad#3]
Hi, great work, I'm new to granular but this is fab, many thanks!

It's a tiny thing but the title of the multiplier knob in the modulators shows as "mutl" - this is meant to be "mult" I think! I searched the code https://github.com/publicsamples/Oi-Grandad/search?q=mutl and it occurs in two XML files, maybe it's just a matter of correcting those.

Many thanks again!
Andy

**Comment by modularsamples** [comment]
Thanks for this Andy. My eye sight isn't what it used to be! I'll correct this shortly.

Best
Rick

**Comment by modularsamples** [comment]
Okay, this is fixed as of the latest release. Thanks for helping out!
