### ISSUE TITLE
2.4b presets/settings window problem

### ISSUE THREAD

**Issue by fotisandstuff** [publicsamples/Oi-Grandad#32]
Hello! I'm having trouble with the presets and settings window. When I press the button, it appears behind the four samplers. I'm using Reaper on Win 10 x64.

![image](https://github.com/publicsamples/Oi-Grandad/assets/44263494/7e4ce080-ded4-4744-ac5d-71303611dcc2)

**Comment by RickTaylor79** [comment]
Oops! I'll upload a fix tomorrow. Thanks for the report.
