### ISSUE TITLE
trouble getting started

### ISSUE THREAD

**Issue by billmaxvoxpax** [publicsamples/Oi-Grandad#36]
Hi, I am not even sure I am using this correctly.  I apologize if I am in error.
I downloaded oi.grandad.vst3.linux.tar.xz and put the oi grandad vst3 folder in the home/.vst3 folder on my computer.
I am using pop_os and ardour.  the gui shows up as I expected but I cannot get it to accept a sound file by dropping, and no sound browser seems to work either.  what have I goofed.  it seems pretty straight forward so I am a bit of a loss.
thanks in advance for any help.  I really hope I can get this to work, I saw it on venus theory's youtube vid and was VERY IMPRESSED.
sincerely
billmaxvoxpax

**Comment by RickTaylor79** [comment]
Hi, thanks for the report. 

Unfortunately, I've no experience with either Pop os, or ardour. Is there any chance you could try with a different DAW, or maybe Carla? To clarify, right clicking on the sample window doesn't open a file browser? There have been [previous reports](https://github.com/publicsamples/Oi-Grandad/issues/11#issuecomment-1340466517) of drag & drop not working, but in that case the file browser seemed fine. 

I'll see if I can get Pop up and running later, it would be helpful to know which version you are using. 

Cheers
Rick

**Comment by billmaxvoxpax** [comment]
Hi Rick, thanks for getting back to me.
I was able to open it in an evaluation copy of reaper.  I prefer ardour.
my version of Pop is: Pop!_OS 22.04 LTS

I am not impatient on this.  I am a guitarist, and am new to
midi/synthesis,  and am trying to learn a couple of synths.  so I have
plenty to do...
but I am very impressed with what I have seen.

btw, I have had a very good experience with the folks at system76.  is
there any question I can put to them that could help?

I am eager to try to incorporate oi-grandad, but I realize you've got
plenty on your plate, so I get it if this is a low priority.
thanks
bill

**Comment by billmaxvoxpax** [comment]
Hi Rick, I apologize for my ignorance. but I am unsure of where the folders
are to go.
I tried putting Oi-Grandad-1.5 in place of oi grandad.vst3 in the
home/.vts3 folder.
I also put oi grandad.vst3 back and put Oi-Grandad-1.5 inside of it, as
well as on try of Oi-Grandad-1.5 into home/.vst3/oi grandad.vst3/Contents
and then into home/.vst3/oi grandad.vst3/Contents/x86_64-linux
all to no avail.  I believe I am missing part of the procedure.  I again
apologize for the hassle.

**Comment by RickTaylor79** [comment]
Hi Bill, sounds like you've downloaded the repository, rather than the plugin. 

This is the file you need:

https://github.com/publicsamples/Oi-Grandad/releases/download/1.1.5/oi.grandad.Lin.VST3.tar.xz

**Comment by billmaxvoxpax** [comment]
Hi Rick,  It won't let me dragNdrop, but I was able to set up a folder and
right click to use the file browser.  I now have a drum sample in there.
so, yeah!!!!  you are amazing thank you.  I now feel like the dog that
caught the car!  I got to go play with this thing and see what I can do.
thanks again!
