### ISSUE TITLE
Logic Pro 10.6.3 - Crash report

### ISSUE THREAD

**Issue by SomeoneCalledRob** [publicsamples/Oi-Grandad#4]
Buffer size set to 512. Crash happened after dragging my own samples into the four slots. It lasted only a few seconds of playing before quitting. I've attached the crash report.

[Logic Crash.txt](https://github.com/publicsamples/Oi-Grandad/files/9678798/Logic.Crash.txt)

**Comment by modularsamples** [comment]
Hey, thanks for the report. I've tried the plugin on a similar system (10.15, logic 10.6.3. 2012 iMac) and wasn't able to get it to crash, which is odd. Are you able to load the presets okay? Just wondering if there's something different about your samples.. It can be funny about samples smaller than 1mb, but normally it would just stop making a sound. 

This latest release updates the HISE code and may just fix it, but I'm not super hopeful:

https://github.com/publicsamples/Oi-Grandad/releases/download/0.9.2/oi.grandad.AU.Mac.zip

**Comment by SomeoneCalledRob** [comment]
Presets load alright and don't cause crashing. I had used short < 1MB samples previously, but when using larger samples there was no crashing. I then checked my buffer size and I had put it back down to 256, but there was no problem.

Installed 0.9.2. Tried using < 1MB samples and the crash happened again.

**Comment by modularsamples** [comment]
Okay, this is expected behaviour (for now). Best to keep to larger samples for the time being.

**Comment by modularsamples** [comment]
If you want to use those shorter samples, I suggest making "chains" out of them. So, a longer file containing the samples one after another (see the "Chains" folder in the preset folder for examples). This not only gets round this bug, but can open up some interesting creative possibilities.

**Comment by SomeoneCalledRob** [comment]
OK, thanks.
