### ISSUE TITLE
The file browser do not open in GNOME. 

### ISSUE THREAD

**Issue by tonilink** [publicsamples/Oi-Grandad#41]
Tested v 1.1.6 in GNOME 45/46 with Fedora 39/40, Wayland; and Debian 12.5 and Debian Sid with GNOME 43.9 and GNOME 46, Wayland.

**Comment by tonilink** [comment]
Only the 1.1.15 is working and opening the file browser. But, when we open it, the plugin interface says it is the 1.1.14 version.

**Comment by RickTaylor79** [comment]
Will look into this for the next release. You should still be able to drag and drop samples in the meantime.

**Comment by tonilink** [comment]
Today I'm testing using Fedora 39 with KDE Plasma, the behavior is the same. Unfortunately drag and drop is also not working.

https://github.com/publicsamples/Oi-Grandad/assets/1645829/da71adbb-42c9-405f-a573-35be80a9f6c0

**Comment by RickTaylor79** [comment]
Tested this last week in Ubuntu 20 (GNOME 3.36)/Reaper last week and everything seemed hunky-dory. 

I use Ubuntu 'cos it's the go-to distribution for non-linux users :) But if there's a "golden" distro for compiling plugins on, please tell me about it. I"m happy to do Linux builds, but I really don't feel like supporting _every_ distro and desktop environment under the sun.

**Comment by RickTaylor79** [comment]
Sorry, wrong button! Mondays!

**Comment by tonilink** [comment]
Debian could be a good option, it's reliable and many plugins and DAW developers utilize it to build their projects. Many other distros are based on Debian, including Ubuntu.
Red Hat is also rock solid, but paid.

**Comment by RickTaylor79** [comment]
Could you tell me if [this plugin](https://github.com/publicsamples/Quetzalcoatl/releases) works for you? Like Oi, Grandad! it was built with Ubuntu 20, but on a different machine with various updates.  You can test the file import on the samples page, just import a wav from there. If it works, a fresh build of OG should too.

**Comment by tonilink** [comment]
![Screenshot from 2024-06-06 11-55-05](https://github.com/publicsamples/Oi-Grandad/assets/1645829/b29da566-79ef-4096-8e3f-5b16d041e23c)
![Screenshot from 2024-06-06 11-56-23](https://github.com/publicsamples/Oi-Grandad/assets/1645829/828723a6-e93e-4d1f-a6bd-a289c78cc4cb)


0.6.0 and 0.6.2 are giving this error.

**Comment by RickTaylor79** [comment]
Ah, sorry about that! The tar file is the wrong size to begin with, no idea how that happened. Anyway, here's a working copy:

https://github.com/publicsamples/Quetzalcoatl/releases/download/0.6.2/Quetzalcoatl.vst3.tar.xz

**Comment by tonilink** [comment]
It can load sample by draging and droping. But the place that we should drop is strange, as you can see in the video. When I drop it in the second slot it goes to another.

Could it be a Hise bug, or something with Wayland or XDG Portal?

https://youtu.be/ysgpoJTFli0

**Comment by tonilink** [comment]
https://github.com/publicsamples/Oi-Grandad/assets/1645829/b1b5c5b3-9d93-4daf-98c4-ee06c7f54f74

Ok, I tested Oi Grandad again dropping the sample in random places in the interface, it loaded in the 4th slot, I don't know why.
I tried to do the same to load something in the 3th slot and them it crashed.

**Comment by RickTaylor79** [comment]
Okay, I think the file browser not showing up is resolved. Try this version, it bypasses your native file browser, a bit annoying but it should work.

https://github.com/publicsamples/Oi-Grandad/releases/download/1.1.6/oi.grandad.Linux.BypassNativeFileBrowser.vst3.tar.xz

No, idea why drag and drop is behaving this way, it's almost like the positioning is off..

**Comment by tonilink** [comment]
Yes! This one is working, it opens a windows where I can select a sample. Thank you!
I'm loving to experiment with your plugin.

**Comment by RickTaylor79** [comment]
Nice one!  I got a pretty big update for it in the works, so keep an eye out.

Closing for now, but if you have any other questions just ask.
