### ISSUE TITLE
Built on linux, but plugin still fails to load on reaper

### ISSUE THREAD

**Issue by guysoft** [publicsamples/Oi-Grandad#44]
Hey, 
Tried to build on linux since the pre-built binary is not loading for me on reaper. However it seems that that too fails to load.

However reaper lists it in the "failed to load plugins" dropdown.
Is there anything else I can do? or debug somehow?

Log how I built to see if anything is wrong:
Followed: https://github.com/publicsamples/Quetzalcoatl/wiki/Build-it-yourself
Compiled HISE standalone, but when I try and open the project I get:
![Screenshot_20240614_205257](https://github.com/publicsamples/Oi-Grandad/assets/325670/ac405c3e-c3ca-4db1-8d6b-64e87b2753aa)

There are a few errors like that with the number incrementing.
Then it does open and I see this:
![Screenshot_20240614_205609](https://github.com/publicsamples/Oi-Grandad/assets/325670/a17e0995-a856-4e8f-8f7e-cb0568bf4d6e)
I had to disable IPP intel (I am using amd) for to compile. I get an .so, but when I place it is still not detected.

Got a make file, built. says in the end:

```
+ echo Compiling finished. Cleaning up...
Compiling finished. Cleaning up...
```
I get a file at ``./Builds/LinuxMakefile/build/oi grandad.vst3/Contents/x86_64-linux/oi grandad.so`` and copied it to the reaper plugin folder.

Also tried to compile as standalone to see if I could debug that, but I get:

```

+ make CONFIG=Release AR=gcc-ar -j14
make: *** No rule to make target '../../JuceLibraryCode/JucePluginDefines.h', needed by 'build/intermediate/Release/Plugin_124bbd3c.o'.  Stop.
+ echo Compiling finished. Cleaning up...
Compiling finished. Cleaning up...
```

**Comment by RickTaylor79** [comment]
Hi there. 

Hmm, I've tested on Ubuntu 20 in Reaper and it loads fine here. Have you tried the [previous version](https://github.com/publicsamples/Oi-Grandad/releases/tag/1.1.6)?  

So the the "Error loading script" messages can be ignored, this comes up every time I load the project in Linux. Also it looks like the UI has some missing bits, it should look like this:

<img width="940" alt="Screenshot 2024-06-15 at 10 28 56" src="https://github.com/publicsamples/Oi-Grandad/assets/53375860/cf7e2da6-6030-40d7-9398-0417c888bd19">

You might try loading the Archive file, it should bypass the script message and _might_ resolve the UI thing. 

![archive](https://github.com/publicsamples/Oi-Grandad/assets/53375860/0f593cd6-dfb8-4dfd-bafc-13a0f7e0dba4)

 It looks like the plugin compiled successfully, you're just copying the wrong file. The "oi grandad.vst3" folder (and its contents) is the plugin, copy that instead.

**Comment by guysoft** [comment]
The ``oi grandad.vst3``` folder just has that file in a folder structure:
```
~/tmp/Oi-Grandad/oi grandad/Binaries/Builds/LinuxMakefile$ find build/oi\ grandad.vst3/
build/oi grandad.vst3/
build/oi grandad.vst3/Contents
build/oi grandad.vst3/Contents/x86_64-linux
build/oi grandad.vst3/Contents/x86_64-linux/oi grandad.so
```
It seems like if I copy the folder it indeed works! Perhaps its worth writing that in the docs, that you need the whole folder.
Also if I place the one I compiled the number labels that are missing in HISE are indeed missing in the one I compiled.
I used HISE 4.0.0](https://github.com/christophhart/HISE/releases/tag/4.0.0) was relesaeed 3 days ago, perhaps there is a breaking thing there for the project file.

I am having issues getting sounds only the top right one works for me, if the drune switch is on. Not sure if that is because I am missing something or not. I am off the the tutorials on that. Thanks!

**Comment by RickTaylor79** [comment]
> I am having issues getting sounds only the top right one works for me, if the drune switch is on. Not sure if that is because I am missing something or not. I am off the the tutorials on that. Thanks!

It should work as expected, any problems let me know!
> 
> Also - the new version is missing the native file picker build, which is actually better on KDE (has bookmarks and remembers last location).

Yeah, I know it's  not ideal but several people reported problems with the native browsers in Ardour, so it's compromise.
