### ISSUE TITLE
LINUX .tar.xz file does not unzip

### ISSUE THREAD

**Issue by CodesoundR** [publicsamples/Oi-Grandad#46]
Linux Mint_x64 - Oi-Grandad 2.00b

Hi,
Thanks for this amazing Project! I inform you that the .tar.xz file does not unzip

```
codesound@codesound:~/Downloads$ tar -xf oi.grandad.vst3.Linux.tar.xz
xz: (stdin): Unexpected end of input
tar: Unexpected EOF in archive
tar: Unexpected EOF in archive
tar: Error is not recoverable: exiting now
codesound@codesound:~/Downloads$ 
```

Regards

**Comment by RickTaylor79** [comment]
Thanks for letting me know. I've upload a working file here:

https://github.com/publicsamples/Oi-Grandad/releases/tag/v2.0.0b

**Comment by CodesoundR** [comment]
> Thanks for letting me know. I've upload a working file here:
> 
> https://github.com/publicsamples/Oi-Grandad/releases/tag/v2.0.0b

Hi,
thank you so much !!! Now it works
I discovered this plugin thanks to this channel that showed it:
https://www.youtube.com/watch?v=wLYjiri_9EI

Now I can try it. Thanks again!
Regards

**Comment by RickTaylor79** [comment]
Thanks for sharing. I love seeing what other people do with this thing.
