### ISSUE TITLE
Are there any v2 presets?

### ISSUE THREAD

**Issue by MusicMan74** [publicsamples/Oi-Grandad#47]
(on Windows)
I copied the 'oi grandad' folder unzipped from 

https://github.com/publicsamples/Oi-Grandad/releases/download/1.1.2/AdditionalContent.zip

into 

C:\Users\\[UserName]\AppData\Roaming\ModularSamples

but the plugin does not recognize any factory presets...

What am I doing wrong?

TIA

**Comment by RickTaylor79** [comment]
I've just uploaded some, just a handful but they should be enough to get started:

https://github.com/publicsamples/Oi-Grandad/releases/tag/v2.0.0b

Keep in mind, as of v2 presets are installed to C:\ProgramData\modularsamples\ (makes things a bit easier, no need to look for hidden folders).

If you're looking for more audio to throw at, have a look at this post:

https://github.com/publicsamples/Oi-Grandad/discussions/6
