### ISSUE TITLE
Oi-Grandad is NOT VISABLE IN ABLETON SUITE 12!

### ISSUE THREAD

**Issue by jamesbtex** [publicsamples/Oi-Grandad#48]
I'm running Windows 11 Pro.
I made a new folder under the VST3 folder called "GRANDAD". Then I placed the VST3 file in that folder C:\Program Files\Common File\VST3\GRANDAD\oi grandad.vst3. I also downloaded, unzipped and placed the contents folder into the correct location mentioned in the release notes. 

Next, I started Ableton, let it scan for new plugins and Ableton sees the plugin during initial scanning because I can see in listed in the bottom left information box while it's scanning. However, once scanning is finished, I try locate the plugin but I can't it listed anywhere under Plug-ins!

Just to be sure I deleted the VST3 file, downloaded, unzipped it, opened Ableton and let it scan and I got exactly the same results! 
I can't find it anywhere listed under plug-ins. 

QUESTION:
Is this plugin a 64bit plugin, or a 32bit plugin?
This version of windows won't work with a 32bit plugin unless a wrapper is used. 
However, without the wrapper, the plugin will show the exact same behavior, when Ableton is scanning, it sees it, but not after Ableton is finished scanning.

If it is a 64bit plugin, then something is broken.

**Comment by RickTaylor79** [comment]
Hmm, that's odd. It seems fine here using Live 12 demo. Have you tried putting it directly in the VST3 folder?  Are you sure you have the Windows version? https://github.com/publicsamples/Oi-Grandad/releases/download/v2.0.0b/oi.grandad.VST3.WIN.zip

You could try pressing  rescan while holding ALT in  the plugin settings, this will clear your plugin cache and rescan everything (might take some time if you have a lot of VSTs installed).

**Comment by jamesbtex** [comment]
Yes it’s in the vst3 folder and yes I have the windows version.

 

Question, when you are viewing it in the Ableton Live Demo, what Creator folder name is it listed under?

 

In other words, I’m sure that you are aware that Ableton has it’s own Subfolder directory structure. I can physically list a plugin somewhere under the VST3 directory, but Ableton will show it listed under a totally different subfolder under the VST3 directory, it depends on what subfolder the manufacture identified within the plugin itself.. 

 

I have seen strange things sometimes in the way manufactures list their plugin.

For example: Say you have a plugin called “Delay” made by “Software CompanyX”.

 

Normally one would go to “Plugins”, then search for “Software CompanyX”, open that folder and they would see “Delay”

However, I have seen where a manufacture chooses not to user their name “Software CompanyX” to list the plugin “Delay”.

 

Instead they may have chosen something weird and unexpected as the location to list their plugin instead of using their company name.

 

For Example: Plugin “Delay” may have been listed under a Parent Company like “World Wide Software”, and “Software CompanyX” is just one of several smaller companies they own.

 

Or, possibly they list it under “Experimental”.

 

In these cases the plugin “Delay” is installed and Ableton does see it, but the User have to figure out “WHERE” is it listed??

 

The folder structure for VST2 plugins, mirrored the actual physical structure.

However that isn’t the case with VST3 plugins. 

 

The manufacture may have it show up in a completely different location then it’s physically located at. 

They may choose to use something unexpected besides their company name when searching for the plugin.

 

James

**Comment by RickTaylor79** [comment]
Hi James. Sorry for the late reply. 

it's listed under modularsamples/oi grandad. This is using Live 12/Windows 11. Not sure what's going wrong your end, have you tried any other DAWs?

![For Rick Screenshot 2024-07-14 161340](https://github.com/user-attachments/assets/9bf55174-e799-437e-bf3e-71944de43c27)

**Comment by jamesbtex** [comment]
Sorry for the late reply. Using the new plugin you gave me it works fine. Thanks.

**Comment by RickTaylor79** [comment]
Thanks for the update!
