### ISSUE TITLE
Missing folder 'modularsamples'

### ISSUE THREAD

**Issue by djhoyling** [publicsamples/Oi-Grandad#49]
I have installed onto a m2 MBP laptop (Sonoma 14.5) with the following instructions:

Extract and run the install package below.
Extract the content zip and copy the oi grandad folder Library/Application Support/modularsamples/

The plugin shows up and works in Ableton however I'm unable to locate the 'modularsamples' folder to install the oi grandad content folder. I've searched my mac and installed a few times to no avail.

Any solutions would be greatly appreciated.

**Comment by RickTaylor79** [comment]
It _should_ ideally create the folder when you launch the plugin. Make sure you're in the root library (not user):

Macintosh HD/Library/Application Support/

If the modularsamples folder doesn't exist here, you can create it manually and drop in oi grandad.

**Comment by djhoyling** [comment]
Excellent thank you! It's working :)
