### ISSUE TITLE
Modulator type b mode playhead position is incorrect

### ISSUE THREAD

**Issue by Woolton** [publicsamples/Oi-Grandad#51]
The stepped modulator mode seems to have the playhead position completely incorrect, the playhead at the end corresponds to 50-60% on the slider rather than 100%.

Also, normal playback pitch seems to be closer to 29% on the pitch encoder rather than 50%

![Ableton_Live_11_Standard_j7bZMLSHAA](https://github.com/user-attachments/assets/27c4a2ec-0f94-41b9-8d25-e81dabe591aa)

**Comment by RickTaylor79** [comment]
Sorry for the late response. The issue with the stepped modulators is fixed as of v2.0.1b. 

The pitch situation is bit complex, there are a variety of quantising options that could put the normal pitch just about anywhere. Pitch controls massively over spec'd to the point where I no longer understand how it works :) next update will simplify this and the similarly overcooked routing section.
