### ISSUE TITLE
Oi-Grandad is not scanned by Audacity on MacOS

### ISSUE THREAD

**Issue by nikodenn** [publicsamples/Oi-Grandad#53]
Audacity Plugin Manager cannot scan Oi-Grandad after its installation

Audacity 3.6.4
OS: MacOS Ventura 13.7
Oi-Grandad version 2.0.0b

**Comment by RickTaylor79** [comment]
Hi, AFAIK audacity doesn't support instrument plugins, unless I'm missing something?

**Comment by nikodenn** [comment]
Yeah, this seems to be a reason. Thank you.

**Comment by RickTaylor79** [comment]
if it's any use you should be able to use a plugin host in Audacity and run any instrument you like (with certain caveats, like no MIDI input). OG is a good candidate for this as it's not entirely dependent on midi control.

**Comment by RickTaylor79** [comment]
Otherwise, I highly recommend the Micheal Norris FX plugins for this kind of thing..
